-- 1) Sales & Revenue: What is total revenue generated by each trip?
select
    t.tripid,
    t.tripname,
    coalesce(sum(r.spotsreserved * t.tripprice), 0) as total_revenue
from trip t
left join reservationtrip rt on rt.tripid = t.tripid
left join reservation r on r.reservationid = rt.reservationid
group by t.tripid, t.tripname
order by total_revenue desc;

-- 2) Sales & Revenue: How does monthly revenue trend over time (excluding cancelled reservations)?
select
    year(r.reservationdate) as revenue_year,
    month(r.reservationdate) as revenue_month,
    sum(r.spotsreserved * t.tripprice) as monthly_revenue
from reservation r
join reservationtrip rt on rt.reservationid = r.reservationid
join trip t on t.tripid = rt.tripid
where r.reservationstatus <> 'Cancelled'
group by year(r.reservationdate), month(r.reservationdate)
order by revenue_year, revenue_month;

-- 3) Sales & Revenue: What is the average revenue value per reservation?
select
    avg(res_total.total_amount) as avg_revenue_per_reservation
from (
    select
        r.reservationid,
        sum(r.spotsreserved * t.tripprice) as total_amount
    from reservation r
    join reservationtrip rt on rt.reservationid = r.reservationid
    join trip t on t.tripid = rt.tripid
    group by r.reservationid
) as res_total;

-- 4) Sales & Revenue: Which trips currently have zero reservations (dead inventory)?
select
    t.tripid,
    t.tripname,
    t.tripdate,
    t.tripstatus
from trip t
left join reservationtrip rt on rt.tripid = t.tripid
where rt.reservationid is null
order by t.tripdate;

-- 5) Customer Insights: Who are the top 5 customers by total spending?
select
    c.customerid,
    c.custfirstname,
    c.custlastname,
    coalesce(sum(r.spotsreserved * t.tripprice), 0) as total_spending
from customer c
left join reservation r on r.customerid = c.customerid
left join reservationtrip rt on rt.reservationid = r.reservationid
left join trip t on t.tripid = rt.tripid
group by c.customerid, c.custfirstname, c.custlastname
order by total_spending desc
limit 5;

-- 6) Customer Insights: Which customers are repeat bookers (more than one reservation)?
select
    c.customerid,
    c.custfirstname,
    c.custlastname,
    count(r.reservationid) as reservation_count
from customer c
join reservation r on r.customerid = c.customerid
group by c.customerid, c.custfirstname, c.custlastname
having count(r.reservationid) > 1
order by reservation_count desc, c.custlastname, c.custfirstname;

-- 7) Customer Insights: Which customers have never made any reservation?
select
    c.customerid,
    c.custfirstname,
    c.custlastname,
    c.custemail
from customer c
left join reservation r on r.customerid = c.customerid
where r.reservationid is null
order by c.custlastname, c.custfirstname;

-- 8) Trip/Product Insights: Which trips are most popular by total spots reserved?
select
    t.tripid,
    t.tripname,
    coalesce(sum(r.spotsreserved), 0) as total_spots_reserved
from trip t
left join reservationtrip rt on rt.tripid = t.tripid
left join reservation r on r.reservationid = rt.reservationid
group by t.tripid, t.tripname
order by total_spots_reserved desc, t.tripname;

-- 9) Trip/Product Insights: Which trips are currently at or over max capacity?
select
    t.tripid,
    t.tripname,
    t.maxcapacity,
    coalesce(sum(case when r.reservationstatus <> 'Cancelled' then r.spotsreserved else 0 end), 0) as enrolled_spots
from trip t
left join reservationtrip rt on rt.tripid = t.tripid
left join reservation r on r.reservationid = rt.reservationid
group by t.tripid, t.tripname, t.maxcapacity
having coalesce(sum(case when r.reservationstatus <> 'Cancelled' then r.spotsreserved else 0 end), 0) >= t.maxcapacity
order by enrolled_spots desc;

-- 10) Trip/Product Insights: Which employee guide has the most reservations across their trips?
select
    e.employeeid,
    e.employeefirst,
    e.employeelast,
    count(distinct r.reservationid) as total_reservations
from employee e
left join trip t on t.empid = e.employeeid
left join reservationtrip rt on rt.tripid = t.tripid
left join reservation r on r.reservationid = rt.reservationid
group by e.employeeid, e.employeefirst, e.employeelast
order by total_reservations desc, e.employeelast, e.employeefirst;
